### ISSUE TITLE
Examples for Behat would be great

### ISSUE THREAD

**Issue by bserem** [ddev/ddev-selenium-standalone-chrome#21]
Thanks for this addon, it looks like it can solve an everlasting problem with testing.

The current examples cover nightwatch, dtt and functionaljavascript. It would be great to add an example for Behat JS tests too.

I'm trying things out but I don't see it connecting. Tried:

`behat.yaml`
```yaml
default:
  suites:
    default:
      contexts:
        - FeatureContext
        - Drupal\DrupalExtension\Context\DrupalContext
        - Drupal\DrupalExtension\Context\MinkContext
        - Drupal\DrupalExtension\Context\MessageContext
        - Drupal\DrupalExtension\Context\DrushContext
  extensions:
    Drupal\MinkExtension:
      browserkit_http: ~
      goutte: ~
      selenium2:
        wd_host: 'selenium-chrome:4444'
      base_url: http://web  # Replace with your site's URL
    Drupal\DrupalExtension:
      blackbox: ~
      region_map:
        header: 'header'
      api_driver: 'drupal'
      drupal:
        drupal_root: '/var/www/html/web'
```
and also tried `base_url` to be `https://mysite.ddev.site`

When I run a `@javascript` behat test it just hangs there, forever. Nothing visible on VNC. Terminal errors after 5min:
```bash
  Scenario: I can submit the form                              # features/critical/hold-an-event.feature:5
    Given I am on "/hold-an-event"                             # Drupal\DrupalExtension\Context\MinkContext::visit()
      Could not open connection: Could not start a new session. New session request timed out
      Build info: version: '4.1.4', revision: '535d840ee2'
      System info: host: 'aa016e9f8e81', ip: '172.19.0.3', os.name: 'Linux', os.arch: 'amd64', os.version: '6.1.0-3-amd64', java.version: '11.0.14'
      Driver info: driver.version: unknown (Behat\Mink\Exception\DriverException)
    And I fill in "edit-first-name" with "Alfred"              # Drupal\DrupalExtension\Context\MinkContext::fillField()
    And I fill in "edit-last-name" with "Bester"               # Drupal\DrupalExtension\Context\MinkContext::fillField()
    And I fill in "edit-email" with "alfredbester@example.com" # Drupal\DrupalExtension\Context\MinkContext::fillField()
    When I press the "Next" button                             # Drupal\DrupalExtension\Context\MinkContext::pressButton()
    Then I should see "Event Date"                             # Drupal\DrupalExtension\Context\MinkContext::assertPageContainsText()

--- Failed scenarios:

    features/critical/hold-an-event.feature:5

1 scenario (1 failed)
6 steps (1 failed, 5 skipped)
5m0.74s (7.36Mb)
```

The IP is correct, checked it from inside VNC.

PS: Chromium will ask the SSL cert to be accepted, not sure if this is an issue
