### ISSUE TITLE
How do you adjust with width and height of the Chrome driver screen?

### ISSUE THREAD

**Issue by nessthehero** [ddev/ddev-selenium-standalone-chrome#43]
Hello,

I'm trying to get the webdriver screen to be larger. I've tried things like adding "SCREEN_WIDTH" and "SCREEN_HEIGHT" to the web_environment array in config.yaml, and adding a flag in my behat configuration. It does not seem to be working.

I'm using Behat so there is a behat.xml file being loaded to configure Mink and all that other stuff.

Any ideas on how this is done?

My behat.xml (Some of it)
```
default:
  extensions:
    Drupal\MinkExtension:
      ajax_timeout: 20
      files_path: '/var/www/html/behat/test-files'
      base_url: 'http://cmu.ddev.site/'
      browser_name: chrome
      goutte: ~
      selenium2:
        wd_host: http://selenium-chrome:4444/wd/hub
        capabilities:
          chrome:
            switches:
              - "--window-size=2560,1440"
              - "--disable-gpu"
              - "--no-sandbox"
              - "--disable-dev-shm-usage"
```
